---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-workarea-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi


