---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi


