apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-config
data:
  config: |
    [${PG_STANZA_NAME}]
    pg1-path=/var/lib/postgresql/data

    [global]
    repo1-type=gcs
    repo1-path=/backups/pg/${PG_STANZA_NAME}
    repo1-gcs-bucket=${PG_BUCKET}
    repo1-gcs-key=/secrets/key.json
    process-max=4
    repo1-retention-full=2

    [global:archive-push]
    compress-level=3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-init
data:
  init: |
    #!/bin/bash
    set -e
    pgbackrest --stanza=${PG_STANZA_NAME} --log-level-console=info stanza-create
