ARG ALPINE_VERSION=3.16
FROM golang:1.19-alpine${ALPINE_VERSION} as builder
RUN apk --no-cache add k3s \
	&& go install github.com/groundcover-com/murre@v0.0.3

FROM alpine:${ALPINE_VERSION}
COPY --from=builder /go/bin/murre /usr/local/bin/
COPY --from=builder /usr/bin/k3s /usr/local/bin/
COPY --from=builder /usr/bin/kubectl /usr/local/bin/
RUN apk --no-cache add bash nmap util-linux \
	&& mkdir /workspace
WORKDIR /workspace

ENTRYPOINT ["/bin/bash"]



