apiVersion: v1
kind: Pod
metadata:
 name: env-kustom-secret
spec:
 containers:
 - name: envars-test-container
   image: busybox
   command: ["printenv"]
   env:
   - name: TEST_USER
     valueFrom:
       secretKeyRef:
         name: test-secrets
         key: test_user
   - name: SECRET_EMAIL
     valueFrom:
       secretKeyRef:
         name: pgadmin-secrets
         key: email
   - name: SECRET_PASS
     valueFrom:
       secretKeyRef:
         name: pgadmin-secrets
         key: password

