---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14.5-alpine
          name: postgresql
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-svc
          volumeMounts:
            - name: pg-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-persistent-storage
          persistentVolumeClaim:
            claimName: pg-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
   - port: 5432
     targetPort: postgres-svc
  selector:
   app: postgres

